# Generated by Django 4.1.6 on 2023-02-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_thumbnail_image_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=('gender', 'male'), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to='user_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(default=('mobile', 234556), max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(upload_to='featured_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(upload_to='thumbnail_images/'),
        ),
    ]
