# Generated by Django 4.1.6 on 2023-02-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_options_remove_comment_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='Good', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=100),
        ),
    ]
